config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post '/graphql', to: 'graphql#execute'

  api_version(module: 'api/v1', path: { value: 'api/v1' }) do
    get 'session/get_user_token_from_facebook_id' => 'sessions#user_token_from_facebook_id'
    get 'session/get_user_token_from_devise' => 'sessions#user_token_from_devise'

    namespace :reports do
      resources :categories, only: [:index]
      get 'category/:id/sub_categories' => 'sub_categories#index'
      resources :reports, only: [] do 
        get 'get', on: :collection
      end
    end

    resources :categories, only: [:index]

    resources :lines, only: [] do 
      get 'get', on: :collection
    end

    get 'users' => "users#show"

    resources :sites, only: [:index, :create, :show] do
      get 'stats', on: :member
      get 'pictures', on: :member
      get 'comments', on: :member
      post 'comment' => 'sites#comment', on: :member
      get 'near', on: :collection
      get 'count', on: :collection
      get 'get', on: :collection
      get 'cluster', on: :collection
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /en|es|fr|dummy/ do

    devise_for :users, skip: :omniauth_callbacks
    ActiveAdmin.routes(self)

    resources :rides
    resources :users, only: [:show]
    post '/profile/link_to_facebook_profile' => 'profiles#link_to_facebook_profile'
    delete '/profile/unlink_facebook_profile/:token' => 'profiles#unlink_facebook_profile'

    patch '/sites/:id/rate' => 'sites#rate'
    patch '/sites/:id/comment' => 'sites#comment'

    get '/sites/' => 'sites#show', as: 'show_site'
    resources :reports, only: [:show, :new, :create, :index]
    resources :sites, only: [:show, :new, :create, :index]
    resources :categories, only: :show

    get '/tos' => 'static#tos'
    get '/team' => 'static#team'
    get '/press' => 'static#press'

    get '/newsletters/unsubscribe/:email' => 'newsletters#unsubscribe'
    delete '/newsletters/unsubscribe/:email' => 'newsletters#destroy'

    resources :newsletters
    resources :users

    root to: 'static#index'
  end

  match '/api' => 'static#api', via: :all
  post '/agregar' => 'static#agregar'

end

app/models/site.rb
class Site < ActiveRecord::Base

  after_update :notify_update
  
  scope :not_reviewed, -> { where(has_been_reviewed: false) }
  scope :has_custom_icon, -> { where("custom_icon_file_name is not null") }
  scope :has_picture, -> { where("picture_1_file_name is not null or picture_2_file_name is not null or picture_3_file_name is not null") }
  scope :has_comments, -> { joins(:comments).distinct }

  def activate!
    update(has_been_reviewed: true, is_active: true)
  end

  def deactivate!
    update(has_been_reviewed: true, is_active: false)
  end

  acts_as_commentable
  acts_as_paranoid
  acts_as_mappable default_units: :kms,
                   default_formula: :sphere,
                   distance_field_name: :distance,
                   lat_column_name: :latitude,
                   lng_column_name: :longitude

  belongs_to :category

  belongs_to :user

  delegate :email, :facebook_uid, to: :user, prefix: true, allow_nil: true
  delegate :name, to: :category, prefix: true

  validates :name, presence: true
  validates :category, presence: true
  validates :lonlat, presence: true

  paginates_per 20 # 2cols*10lines

  has_attached_file :picture_1, :styles => { :medium => "660x337>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture_1, :content_type => /\Aimage\/.*\Z/

  has_attached_file :picture_2, :styles => { :medium => "660x337>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture_2, :content_type => /\Aimage\/.*\Z/

  has_attached_file :picture_3, :styles => { :medium => "660x337>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture_3, :content_type => /\Aimage\/.*\Z/

  has_attached_file :custom_icon, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :custom_icon, :content_type => /\Aimage\/.*\Z/

  def latitude=(value)
    factory = RGeo::Geographic.spherical_factory(srid: 4326)
    self.lonlat = factory.point(longitude, value)
  end

  def latitude
    lonlat.try(:y)
  end

  def longitude=(value)
    factory = RGeo::Geographic.spherical_factory(srid: 4326)
    self.lonlat = factory.point(value, latitude)
  end

  def longitude
    lonlat.try(:x)
  end

  def has_custom_icon
    custom_icon.exists?
  end

  def has_picture
    picture_1.exists? || picture_2.exists? || picture_3.exists?
  end

  def has_comments
    comments.count > 0
  end

  def icon_url
    if custom_icon.exists?
      custom_icon.url
    else
      category.icon.url 
    end
  end

  def nearest_sites
    Site.within(0.300, origin: self).where('sites.is_active' => true).reject { |e| e == self }
  end

  def nb_rating
    Rating.where(['site_id = ?',  id]).count
  end

  def rating
    Rating.where(['site_id = ?',  id]).average(:rate)
  end

  def user_rating(user_id)
    Rating.where(['site_id = ? and user_id = ?', id, user_id]).first_or_initialize.rate
  end

  protected

  def notify_update
    if lonlat_changed? || name_changed? || description_changed? || category_id_changed? then
      if user
        DefaultMailer.notify_site_update_creator(user, self).deliver if user.receive_notifications
      end

      comments.map { |c| c.user }.compact.uniq.each do |user|
        DefaultMailer.notify_site_update_commenter(user, self).deliver if user.receive_notifications
      end
    end
  end

end

app/controllers/api/v1/sites_controller.rb
module Api
  module V1
    class SitesController  < ActionController::Base
      def index
        @sites = Site.with_deleted.all
      end

      def show
        @site = Site.find(params[:id])
      end

      def stats
        @site = Site.find(params[:id])
      end

      def pictures
        @site = Site.find(params[:id])
      end

      def comments
        @comments = Site.find(params[:id]).comments
      end

      def comment
	@site = Site.find params[:id]
	comment = @site.comments.create
	comment.comment = params[:comment]
	comment.user = User.find_by_token params[:token]

	comment.save

        render json: {result: "ok"}
      end

      def count
        categories_id = params[:categories].split(",").map(&:to_i)

        sw = params[:sw].split(",")
        ne = params[:ne].split(",")

        lng = 1
        lat = 0

        viewport = "POLYGON((#{sw[lng]} #{ne[lat]},#{ne[lng]} #{ne[lat]},#{ne[lng]} #{sw[lat]},#{sw[lng]} #{sw[lat]},#{sw[lng]} #{ne[lat]}))"

        count = Site.joins(:category).where('sites.is_active' => true, 'categories.is_active' => true, 'sites.category_id' => categories_id).where(["ST_WITHIN(sites.lonlat::geometry, ST_PolygonFromText(?, 4326))", viewport]).count
        render json: { count: count }
      end

      def get

        categories_id = "NULL"
        categories_id = params[:categories] if params[:categories].present?

        sw = params[:sw].split(",")
        ne = params[:ne].split(",")

        lng = 1
        lat = 0

        viewport = "POLYGON((#{sw[lng]} #{ne[lat]},#{ne[lng]} #{ne[lat]},#{ne[lng]} #{sw[lat]},#{sw[lng]} #{sw[lat]},#{sw[lng]} #{ne[lat]}))"

        query_sites = %{
        select row_to_json(q) as json from (
            select COALESCE(array_to_json(array_agg(row_to_json(t))), '[]') as sites from (
                    select s.id, s.name,
                    COALESCE(
                      '/system/sites/custom_icons/' ||
                      substring(lpad(s.id::text, 9, '0') from 1 for 3) || '/' || 
                      substring(lpad(s.id::text, 9, '0') from 4 for 3) || '/' ||
                      substring(lpad(s.id::text, 9, '0') from 7 for 3) || '/original/' || s.custom_icon_file_name || '?' || EXTRACT(EPOCH FROM date_trunc('second', s.custom_icon_updated_at))
                    ,
                      '/system/categories/icons/' ||
                      substring(lpad(c.id::text, 9, '0') from 1 for 3) || '/' || 
                      substring(lpad(c.id::text, 9, '0') from 4 for 3) || '/' ||
                      substring(lpad(c.id::text, 9, '0') from 7 for 3) || '/original/' || c.icon_file_name || '?' || EXTRACT(EPOCH FROM date_trunc('second', c.icon_updated_at))
                    ) as icon_url,
                    ST_X(s.lonlat::geometry) longitude,
                    ST_Y(s.lonlat::geometry) latitude
                    from sites s 
                    join categories c on c.id = s.category_id and c.deleted_at is NULL 
                    where s.deleted_at is NULL
                    and s.is_active = 't'
                    and c.is_active = 't'
                    and c.id IN (#{categories_id})
                    and (ST_WITHIN(s.lonlat::geometry, ST_PolygonFromText('#{viewport}', 4326)))
            ) t
            ) q
        }

        results = Site.connection.execute(query_sites)
        @sites_as_json = results.first['json'].html_safe

        render json: @sites_as_json

      end

      def cluster
        
        zoom = params[:zoom].to_i
        delta = 40
        delta = delta/zoom unless zoom == 0
    
        query_cluster = %{
          select array_to_json(array_agg(row_to_json(p))) as json from (
          SELECT t.count, ST_y(t.center) latitude, ST_x(t.center) longitude FROM (
          SELECT
              COUNT( s.lonlat ) AS count,
              ST_AsText( ST_Centroid(ST_Collect( s.lonlat::geometry )) ) AS center
          FROM sites s
          join categories c on c.id = s.category_id
          where s.deleted_at is null
          and s.is_active = 't'
          and c.deleted_at is null
          and c.is_active = 't'
          GROUP BY
              ST_SnapToGrid( lonlat::geometry, #{delta}, #{delta})
          ) t
          ORDER BY
              count DESC
          ) p
        }

        results = Site.connection.execute(query_cluster)
        @cluster_as_json = (results.first['json'] || '{}').html_safe

        render json: @cluster_as_json
      end

      def create
        @site = Site.new(site_params)

        @site.origin = 'API'

        params.permit(:token)
        @site.user = User.find_by_token params[:token]

        respond_to do |format|
          if @site.save
            format.html { render nothing: true }
            format.json { render nothing: true }
          else
            format.html { render :new }
            format.json { render json: @site.errors, status: :unprocessable_entity }
          end
        end
      end

      def near
        lat, lng = params[:ll].split(',')
        origin = Geokit::LatLng.new(lat, lng)
        @sites = Site.all.within(0.300, origin: origin).where('sites.is_active' => true)

        @sites = @sites.sort_by do |site|
          p = Geokit::LatLng.new(site.latitude, site.longitude)
          (p.distance_to(origin,  unit: :kms ) * 1000).round
        end
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def site_params
        params.require(:site).permit(:name, :description, :latitude, :longitude, :is_active, :deleted_at, :category_id, :has_been_reviewed)
      end
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy, :rate, :comment]

  # GET /sites
  # GET /sites.json
  def index
    authorize Site
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    authorize @site
  end

  # GET /sites/new
  def new
    authorize Site
    @site = Site.new

    return unless params[:pos]

    @latlng = params[:pos].split(',')

    factory = RGeo::Geographic.spherical_factory(srid: 4326)
    @site.lonlat = factory.point(@latlng[1], @latlng[0])
  end

  # GET /sites/1/edit
  def edit
    authorize @site
  end

  # POST /sites
  # POST /sites.json
  def create
    authorize Site
    @site = Site.new(site_params)

    @site.origin = 'WEB'
    @site.user = current_user

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    authorize @site
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    authorize @site
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  # PATCH /sites/1/rate
  def rate
    authorize @site
    rating = Rating.where(site_id: @site.id, user_id: current_user.id).first_or_create(site_id: @site.id, user_id: current_user.id)

    rating.rate = params[:rate]

    flash[:notice] = I18n.t(:rate_cant_be_empty) unless rating.save

    redirect_to site_path(@site)
  end

  # PATH /sites/1/comment
  def comment

    authorize @site

    comment = @site.comments.create
    comment.comment = params[:comment]
    comment.user = current_user
    
    flash[:notice] = I18n.t(:comment_cant_be_empty) unless comment.save

    @site.comments.map { |c| c.user }.compact.uniq.reject { |u| u == current_user || u == @site.user }.each do |user|
      DefaultMailer.notify_site_new_comment(user, @site).deliver if user.receive_notifications
    end

    redirect_to site_path(@site)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_site
    @site = Site.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def site_params
    factory = RGeo::Geographic.spherical_factory(srid: 4326)
    lonlat = factory.point(params[:site][:longitude], params[:site][:latitude])
    params.require(:site).permit(:name, :description, :is_active, :deleted_at, :category_id, :has_been_reviewed, :picture_1).merge(:lonlat => lonlat)
  end
end

app/views/sites/_form.html.erb
<div class="row">
<%= form_for(site, html: { id: "form" }) do |f| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="col-md-4">
    <div class="thumbnail" id="map-canvas" style="width:100%; height: 350px;"></div>
  </div>
  <div class="col-md-8">

    <% if !user_signed_in? %>
      <div class="callout callout-warning">
        <h4><%= t(:you_are_not_logged_in) %></h4>
        <p><%= t(:site_will_be_rewarded_to_anonymous) %></p>
      </div>
    <% end %>

    <!-- Default box -->
    <div class="box">
      <div class="box-header">
        <h3 class="box-title"><%= t(:details) %></h3>
      </div>
      <div class="box-body">
        <div class="form-group">
          <%= f.label t(:name) %><br>
          <%= f.text_field :name, class:"form-control", required: true  %>
        </div>
        <div class="form-group">
          <%= f.label t(:description) %><br>
          <%= f.text_area :description, class:"form-control" %>
        </div>
        <%= f.hidden_field :latitude %>
        <%= f.hidden_field :longitude %>
        <div class="form-group">
          <%= f.label t(:category) %><br>
          <%= f.select(:category_id, Category.all.where(:variety => 'SIT').where(:is_public => true).collect {|c| [ c.name, c.id ] }, { include_blank: true }, class: "form-control")  %>
        </div>
        <div class="form-group">
          <%= f.label :picture_1, t(:picture) %><br>
          <%= f.file_field :picture_1 %>
        </div>
      </div>
    </div>


  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="box box-solid">
      <div class="box-body">
        <div class="pull-right">
          <%= link_to t(:back), :root, class: "btn btn-default" %>
          <%= f.submit t(:save), class: "btn btn-primary" %>
        </div>
        <div class="clearfix">
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>


<script type="text/javascript">

function forbiden_words(str) {
  
  var words = ["casa", "home", "oficina", "trabajo", "apto", "apartamento", "colegio", "hogar", "casita", "work", "universidad"]

  var strl = str.toLowerCase()

  for (var i = 0; i < words.length; i++) {
    if (strl.indexOf(words[i]) != -1) {
      return true
    }
  }

  return false;

}


$(function() {
  initialize();
  $('#form').on('submit', function() {
    var name = $('#site_name').val()
    var description = $('#site_description').val()
    
    if (forbiden_words(name) || forbiden_words(description)) {
      return confirm("Por su seguridad, no se aceptan sitios personales, continuar?");
    }

    return true;
  });
})

function initialize() {
  
	var icons = [];

	icons[""] = null;

	<% Category.all.each do |category| %>
	icons["<%= category.id %>"] = "<%= category.icon.url %>";
	<% end %>

	var mapOptions = {
		center: new google.maps.LatLng(0, 0),
		zoom: 2
	};

	var map = new google.maps.Map(document.getElementById("map-canvas"),
			mapOptions);

	<% if (site.latitude && site.longitude) then %>
		map.setCenter(new google.maps.LatLng(<%= site.latitude %>, <%= site.longitude %>));
		map.setZoom(15);
	<% end %>

	var marker = new google.maps.Marker({
	    position: new google.maps.LatLng(<%= site.latitude || 0%>, <%= site.longitude || 0 %>),
	    map: map,
	    draggable: true,
	    title:"<%= site.name %>"
	});

	google.maps.event.addListener(marker, 'dragend', function(evt) {
	    console.log(evt.latLng);
	    document.getElementById('site_latitude').value = evt.latLng.lat();
	    document.getElementById('site_longitude').value = evt.latLng.lng();
	});

	$("#site_category_id").change(function() {
    category_id = $(this).val();
    marker.setIcon(icons[category_id]);
	});

}

</script>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form', :site => @site %>

<%= link_to t(:show), site_path(@site) %> |
<%= link_to t(:back), :back %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table border="1px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Is active</th>
      <th>Has been reviewed</th>
      <th>Category</th>
      <th>Added by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= site.description %></td>
        <td><%= site.latitude %></td>
        <td><%= site.longitude %></td>
        <td><%= bool(site.is_active) %></td>
        <td><%= bool(site.has_been_reviewed) %></td>
	<% if site.category != nil then %>
		<td><%= link_to site.category_name, category_path(site.category) %></td>
	<% else %>
		<td>Does not belong to a category</td>
	<% end %>
	<th><%= site.user_email %> <%= image_tag 'http://graph.facebook.com/picture?type=square', :style => "vertical-align:middle" %></th>
	<td><%= link_to t(:show), site_path(site) %></td>
        <td><%= link_to t(:edit), edit_site_path(site) %></td>
        <td><%= link_to t(:destroy), site_path(site), method: :delete, data: { confirm: t('are_you_sure?') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<%= render 'form', :site => @site %>

app/views/sites/show.html.erb
<% 
  og title: @site.name
  og description: @site.description
  if (has_picture(@site))
    twitter card: "summary_large_image"
    og image: "https://bicimapa.com" + get_first_picture(@site)
  else
    twitter card: "summary"
    og image: "https://bicimapa.com" + @site.category.icon.url
  end
%>

<%= row do %>
  <%= column(4) do %>
    <%= panel do %>
      <div style="width: auto; height: 350px" id="map"></div>
      <%= render partial: "shared/sites/googlemap", locals: {site: @site} %>
    <% end %>
      <%
          images = []
      images << @site.picture_1 if @site.picture_1.exists?
      images << @site.picture_2 if @site.picture_2.exists?
      images << @site.picture_3 if @site.picture_3.exists?
    %>
  <% if images.any? %>
    <%= panel do %>
    <%= carousel(images) %>
  <% end %>
<% end %>
  <% end %>

  <%= column(8) do %>
    <% unless @site.has_been_reviewed %>
      <%= callout(:this_site_has_not_been_reviewed_yet) %>
    <% end %>

    <%= panel("Details") do %>
      <%= attributes_table do %>
        <%= attribute(:name, @site.name) %>
        <%= attribute(:description, @site.description) %>
        <%= attribute(:category, @site.category.name) %>
        <%= attribute(:added_by, added_by(@site)) %>
        <%= attribute(:last_update, time_ago_in_words(@site.updated_at)) %>
        <%= attribute(:rating, rating(@site.rating, @site.nb_rating)) %>

        <% if user_signed_in? %>
          <th><%= t :your_rating %></th>
          <td>
            <%= form_tag("/sites/#{@site.id}/rate", :method => :patch, :style => "display:inline", class: "form-inline") do %>
              <%= number_field_tag :rate, @site.user_rating(current_user), :in => 0..5, :step => 0.5, class: "form-control" %>
              <%= submit_tag t(:"rate"), :disabled => !user_signed_in?, class: "btn btn-default" %>
            <% end %>
          </td>
        <% end %>

      <% end %>
    <% end %>

    <%= panel("Comments") do %>

        <% if user_signed_in? %>
          <%= comment_form %>
        <% else %>
          <%= callout(:you_must_be_logged_in_to_comment) %>
        <% end %>

        <% if @site.comments.any? %>
          <hr/>
        <% end %>

        <% @site.comments.each do |comment| %>
          <%= comment(comment, @site) %>
        <% end %>

    <% end %>

  <% end %>
<% end %>

<%= button_bar do %>
  <%= link_to t(:back), :back, class: "btn btn-danger" %>
<% end %>