config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post '/graphql', to: 'graphql#execute'

  api_version(module: 'api/v1', path: { value: 'api/v1' }) do
    get 'session/get_user_token_from_facebook_id' => 'sessions#user_token_from_facebook_id'
    get 'session/get_user_token_from_devise' => 'sessions#user_token_from_devise'

    namespace :reports do
      resources :categories, only: [:index]
      get 'category/:id/sub_categories' => 'sub_categories#index'
      resources :reports, only: [] do 
        get 'get', on: :collection
      end
    end

    resources :categories, only: [:index]

    resources :lines, only: [] do 
      get 'get', on: :collection
    end

    get 'users' => "users#show"

    resources :sites, only: [:index, :create, :show] do
      get 'stats', on: :member
      get 'pictures', on: :member
      get 'comments', on: :member
      post 'comment' => 'sites#comment', on: :member
      get 'near', on: :collection
      get 'count', on: :collection
      get 'get', on: :collection
      get 'cluster', on: :collection
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /en|es|fr|dummy/ do

    devise_for :users, skip: :omniauth_callbacks
    ActiveAdmin.routes(self)

    resources :rides
    resources :users, only: [:show]
    post '/profile/link_to_facebook_profile' => 'profiles#link_to_facebook_profile'
    delete '/profile/unlink_facebook_profile/:token' => 'profiles#unlink_facebook_profile'

    patch '/sites/:id/rate' => 'sites#rate'
    patch '/sites/:id/comment' => 'sites#comment'

    get '/sites/' => 'sites#show', as: 'show_site'
    resources :reports, only: [:show, :new, :create, :index]
    resources :sites, only: [:show, :new, :create, :index]
    resources :categories, only: :show

    get '/tos' => 'static#tos'
    get '/team' => 'static#team'
    get '/press' => 'static#press'

    get '/newsletters/unsubscribe/:email' => 'newsletters#unsubscribe'
    delete '/newsletters/unsubscribe/:email' => 'newsletters#destroy'

    resources :newsletters
    resources :users

    root to: 'static#index'
  end

  match '/api' => 'static#api', via: :all
  post '/agregar' => 'static#agregar'

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user

  has_attached_file :picture, :styles => { :medium => "600x337>", :thumb => "64x64!" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :start, presence: true
  validates :path, presence: true

  scope :has_picture, -> { where("picture_file_name is not null") }

  def has_picture
    picture.exists?
  end

  default_scope { select('rides.*, ST_Length(path::geography) as length') }

  after_commit :notify_team, on: [:create]

  def notify_team
    AdminMailer.new_ride().deliver_now
  end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index

    authorize Ride

    if Rails.env.production?
      ip = request.remote_ip
    else
      ip = '176.179.249.239'
    end
      
    response = HTTParty.get("http://ip-api.com/json/#{ip}")
    data = response.parsed_response

    @city = data["city"]
    @lon = data["lon"]
    @lat = data["lat"]

    @near_rides = Ride.where(["ST_Contains(ST_Buffer(ST_GeographyFromText('POINT(? ?)'), 25000)::geometry, rides.path)", @lon, @lat]).order(start: :desc).all
    @other_rides = Ride.where(["not ST_Contains(ST_Buffer(ST_GeographyFromText('POINT(? ?)'), 25000)::geometry, rides.path)", @lon, @lat]).order(start: :desc).all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
    authorize @ride
  end

  # GET /rides/new
  def new
    authorize Ride
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
    authorize @ride
  end

  # POST /rides
  # POST /rides.json
  def create

    authorize Ride

    @ride = Ride.new(ride_params)
    @ride.user = current_user

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        @ride.path = ride_params[:path]
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
  
    authorize @ride

    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    authorize @ride
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:name, :description, :start, :end, :path, :user_id, :picture)
    end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= simple_form_for ride do |f| %>

  <%= row do %>
    <%= column do %>
      <%= callout(
        I18n.t(:new_ride_help_message_html, video_url: link_to("https://youtu.be/EBj3U_WJwtA", "https://youtu.be/EBj3U_WJwtA", target: "_blank")),
        "Test",
        :info)
      %>

      
      <% if ride.errors[:path].any? %>
        <%= callout(t(:path_must_be_defined), "Errors", :danger) %>
      <% end %>

      <%= panel do %>
        <div id="map" style="width:100%; height: 500px;"></div>
        <%= render partial: "shared/rides/googlemap", locals: { ride: @ride } %>
      <% end %>
    <% end %>


    <%= column do %>

      <% if !user_signed_in? %>
        <%= callout(t(:you_are_not_logged_in), t(:ride_will_be_rewarded_to_anonymous)) %>
      <% end %>

      <%= panel("Details") do %>
        <%= form_table do %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :start, as: :string %>
          <%= f.input :end, as: :string %>
          <%= f.input :path, as: :hidden %>
          <%= f.input :picture %>
        <% end %>
      <% end %>

    <% end %>

  <% end %>

  <%= button_bar do %>
    <%= link_to t(:back), :root, class: "btn btn-default" %>
    <%= f.submit t(:save), class: "btn btn-primary" %>
  <% end %>

        <script>
          $(function() {
            var options = {
              language: '<%= I18n.locale %>',
              autoclose: true,
              format: 'yyyy-mm-dd hh:ii'
            }
            $('#ride_start').datetimepicker(options);
            $('#ride_end').datetimepicker(options);
          });
        </script>


<% end %>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form', :ride => @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<div class="row">
<div class="col-md-12">
  <section class="content-header">
    <h1><%= t(:listing_rides_near) %> <%= @city %> <span class="badge bg-light-blue"><%= @near_rides.length %></span></h1>
  </section>
  <br/>

      <div class="row">
    <% @near_rides.each do |ride| %>

        <div class="col-md-6">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title"><%= ride.name %> <%= t(:on) %> <%= l ride.start, format: :long %></h3>
            </div><!-- /.box-header -->
            <div class="box-body">
              <%= link_to ride do %>
                <img src="<%= static_map_url(ride.path) %>" style="width: 100%" />
              <% end %>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div>

    <% end %>
      </div>




  <section class="content-header">
    <h1><%= t(:other_rides_in_the_world) %> <span class="badge bg-light-blue"><%= @other_rides.length %></span></h1>
  </section>
  <br/>

      <div class="row">
    <% @other_rides.each do |ride| %>

        <div class="col-md-6">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title"><%= ride.name %> <%= t(:on) %> <%= l ride.start, format: :long %></h3>
            </div><!-- /.box-header -->
            <div class="box-body">
              <%= link_to ride do %>
                <img src="<%= static_map_url(ride.path) %>" style="width: 100%" />
              <% end %>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div>

    <% end %>
      </div>
</div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="box box-solid">
      <div class="box-body">
        <div class="pull-right">
          <%= link_to t(:back), :back, class: "btn btn-danger" %>
          <%= link_to t(:new), new_ride_path, class: "btn btn-primary" %>
        </div>
        <div class="clearfix">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rides/new.html.erb
<%= render 'form', :ride => @ride %>

app/views/rides/show.html.erb
<%= row do %>
  <%= column do %>

    <%= panel do %>
      <div style="width: auto; height: 350px" id="map"></div>
      <%= render partial: "shared/rides/googlemap", locals: { ride: @ride } %>
    <% end %>

    <% if @ride.picture.exists? %>
      <%= panel do %>
        <%= carousel(@ride.picture) %>
      <% end %>
    <% end %>

  <% end %>

  <%= column do %>
    <%= panel("Details") do %>
      <%= attributes_table do %>
        <%= attribute(:name, @ride.name) %>
        <%= attribute(:description, @ride.description) %>
        <%= attribute(:start, I18n.l(@ride.start, format: :short)) %>
        <%= attribute(:end, I18n.l(@ride.end, format: :short)) if @ride.end %>
        <%= attribute(:length, (@ride.length/1000).round(2).to_s + " km") %>
        <%= attribute(:added_by, added_by(@ride)) %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= button_bar do %>
  <% if policy(@ride).update? %>
    <%= link_to t(:edit), edit_ride_path(@ride), class: "btn btn-primary" %>
  <% end %>
  <% if policy(@ride).destroy? %> 
    <%= link_to t(:delete), @ride, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <%= link_to t(:back), :back, class: "btn btn-danger" %>
<% end %>