config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post '/graphql', to: 'graphql#execute'

  api_version(module: 'api/v1', path: { value: 'api/v1' }) do
    get 'session/get_user_token_from_facebook_id' => 'sessions#user_token_from_facebook_id'
    get 'session/get_user_token_from_devise' => 'sessions#user_token_from_devise'

    namespace :reports do
      resources :categories, only: [:index]
      get 'category/:id/sub_categories' => 'sub_categories#index'
      resources :reports, only: [] do 
        get 'get', on: :collection
      end
    end

    resources :categories, only: [:index]

    resources :lines, only: [] do 
      get 'get', on: :collection
    end

    get 'users' => "users#show"

    resources :sites, only: [:index, :create, :show] do
      get 'stats', on: :member
      get 'pictures', on: :member
      get 'comments', on: :member
      post 'comment' => 'sites#comment', on: :member
      get 'near', on: :collection
      get 'count', on: :collection
      get 'get', on: :collection
      get 'cluster', on: :collection
    end
  end

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /en|es|fr|dummy/ do

    devise_for :users, skip: :omniauth_callbacks
    ActiveAdmin.routes(self)

    resources :rides
    resources :users, only: [:show]
    post '/profile/link_to_facebook_profile' => 'profiles#link_to_facebook_profile'
    delete '/profile/unlink_facebook_profile/:token' => 'profiles#unlink_facebook_profile'

    patch '/sites/:id/rate' => 'sites#rate'
    patch '/sites/:id/comment' => 'sites#comment'

    get '/sites/' => 'sites#show', as: 'show_site'
    resources :reports, only: [:show, :new, :create, :index]
    resources :sites, only: [:show, :new, :create, :index]
    resources :categories, only: :show

    get '/tos' => 'static#tos'
    get '/team' => 'static#team'
    get '/press' => 'static#press'

    get '/newsletters/unsubscribe/:email' => 'newsletters#unsubscribe'
    delete '/newsletters/unsubscribe/:email' => 'newsletters#destroy'

    resources :newsletters
    resources :users

    root to: 'static#index'
  end

  match '/api' => 'static#api', via: :all
  post '/agregar' => 'static#agregar'

end

app/views/layouts/_announcement.html.erb
<% announcement = Announcement.current %>

<% if announcement != nil && cookies["announcement_" + announcement.id.to_s] != "hidden" %>

<div class="modal fade" data-show="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close hide_announcement" data-dismiss="modal" data-announcementid="<%= announcement.id %>" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= announcement.try(:heading) || t(:annoucement) %></h4>
      </div>
      <div class="modal-body">
        <p><%= announcement.body %></p>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<% end %>

app/views/layouts/_ascii.html.erb
<!--
                          (Bicimapa!)
            __._. __.. O
           ____ ._..  /\,
                     -|~(*)
        :::::::::.  (*)
    -=-=-=-=-=-=-=-=-=-=-=-=-=-=-
-->

app/views/layouts/_fonts.html.erb
<link href="http://fonts.googleapis.com/css?family=Ruda:400,900,700" rel="stylesheet" type="text/css" />
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" rel="stylesheet" type="text/css" />

app/views/layouts/_newsletter.html.erb
<div class="modal fade" id="newsletter_modal" tabindex="-1" role="dialog" data-show="false">
  <div class="modal-dialog">
    <%= simple_form_for Newsletter.new do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= t(:join_the_bicimappers_familly, count: @bicimappers_count) %></h4>
      </div>
      <div class="modal-body">
        <%= image_tag 'newsletter.png', style: 'width: 100%' %><br/>
        <br/>
        <p><%= t(:receive_the_newsletter) %></p>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
          <input type="email" required class="form-control" name="newsletter[email]" placeholder="<%= t(:email) %>">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn-newsletter btn btn-default" data-dismiss="modal"><%= t(:no_thanks) %></button>
        <%= f.submit t(:save), class: "btn-newsletter btn btn-primary" %>
      </div>
    </div><!-- /.modal-content -->
  <% end %>
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">

var showNewsletter = function() {
  var newsletter_already_shown = localStorage.getItem('newsletter_already_shown') || false;

  if (!newsletter_already_shown) {
    $("#newsletter_modal").modal('show');
    localStorage.setItem('newsletter_already_shown', true);
  }
}

$(function() {
  setTimeout(showNewsletter, 30000);
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= render 'layouts/ascii' %>
        <% og url: url_for(:locale => nil, :host => "bicimapa.com", :protocol => "https") %>
        <% og site_name: "Bicimapa" %>
        <% twitter site: "@bicimapa" %>
        <%= metamagic %>
  <title><%= t :bicimapa %><% if @site && !@site.new_record? %> | <%= @site.category.name %> | <%= @site.name %> <% end %></title>
  <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&libraries=drawing&callback=initMap"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= include_gon %>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
  <%= render 'layouts/fonts' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
	.map-canvas img {
		max-width: none;
	}

	<%= yield :style %>
  </style>
</head>
<body style="padding-top:7px" data-no-turbolink>

	<div class="container-fluid">
<nav class="navbar navbar-default">
      <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
	  </button>
	  <%= link_to t(:bicimapa), :root, class:"navbar-brand" %>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav">
	  <li><%= link_to '<i class="fa fa-facebook"></i>'.html_safe, "https://www.facebook.com/bicimapa", :target => "_blank" %></li>
	  <li><%= link_to '<i class="fa fa-twitter"></i>'.html_safe, "https://www.twitter.com/bicimapa", :target => "_blank" %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-calendar"></i> <%= t :rides %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t(:view_rides), {controller: :rides, action: :index} %></li>
            <li><%= link_to t(:create_new_ride), {controller: :rides, action: :new} %></li>
          </ul>
        </li>
          </ul>

	  <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t(:more) %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to locale: :en do %>
                <%= image_tag "flags/gb.png", class: 'vertical-align: baseline' %>
                <%= t(:english) %>
              <% end %>
          </li>
            <li>
              <%= link_to locale: :fr do %>
                <%= image_tag "flags/fr.png", class: 'vertical-align: baseline' %>
                <%= t(:french) %>
              <% end %>
          </li>
            <li>
              <%= link_to locale: :es do %>
                <%= image_tag "flags/es.png", class: 'vertical-align: baseline' %>
                <%= t(:spanish) %>
              <% end %>
          </li>
          <li class="divider"></li>
            <li><%= link_to '<i class="fa fa-android"></i>'.html_safe + t(:android_app), "https://play.google.com/store/apps/details?id=fr.ylecuyer.colazo&hl=#{I18n.locale}" %></li>
            <li><%= link_to '<i class="fa fa-apple"></i>'.html_safe + t(:ios_app), "https://itunes.apple.com/#{I18n.locale}/app/bicimapa/id851915700" %></li>
            <li class="divider"></li>
					<li><%= link_to t(:press), {controller: '/static', action: :press} %></li>
					<li><%= link_to t(:team), {controller: '/static', action: :team} %></li>
					<li><%= link_to t(:blog), "http://blog.bicimapa.com" %></li>
					<li><%= link_to t(:tos), {controller: '/static', action: :tos} %></li>
					<li><%= link_to t(:newsletter), new_newsletter_path %></li>
          </ul>
        </li>
      </ul>
			    <% case I18n.locale %>
			    <% when :fr %>
				    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank" class="navbar-form navbar-right">
			    <div class="form-group">
					    <input type="hidden" name="cmd" value="_s-xclick">
					    <input type="hidden" name="hosted_button_id" value="UBESRVDN2U992">
					    <input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="Faire un don" class="form-control">
					    <img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
			    </div>
				    </form>
			     <% when :es %>
				    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="navbar-form navbar-right">
			    <div class="form-group">
					    <input type="hidden" name="cmd" value="_s-xclick">
					    <input type="hidden" name="hosted_button_id" value="6TJ46DEGJV7MN">
					    <input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="Donar" class="form-control">
					    <img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
			    </div>
				    </form>
			    <% when :en %>
				    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="navbar-form navbar-right">
			    <div class="form-group">
					    <input type="hidden" name="cmd" value="_s-xclick">
					    <input type="hidden" name="hosted_button_id" value="VJ33P8ECZ5X8G">
					    <input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="Donate" class="form-control">
					    <img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
			    </div>
				    </form>

			     <% end %>

	  <% if user_signed_in? %>
		  <%= link_to(t(:logout), destroy_user_session_path, :method => :delete, class: "btn btn-warning navbar-btn navbar-right", style:"margin-left: 15px") %> 
     	  <% else %>
		  <%= link_to(t(:register), new_user_registration_path, class:"btn btn-success navbar-btn navbar-right", style:"margin-left:7px")  %>   
		  <%= link_to(t(:login), new_user_session_path, class:"btn btn-primary navbar-btn navbar-right")  %>   
	  <% end %>

		
	  <% if user_signed_in? && (current_user.is_moderator || current_user.is_admin) %> 
          <ul class="nav navbar-nav">
	  <li><%= link_to t(:profile), user_path(current_user) %></li>
	  <% if current_user.is_moderator || current_user.is_admin %>
	       <li><%= link_to t(:administration), admin_root_path %></li>
  	  <% end %>
	  </ul>
	  <% end %>

        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
<%= yield %>

	</div>

  <% render 'layouts/newsletter' %>
</body>
</html>

app/views/layouts/devise.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/ascii' %>
    <meta charset="UTF-8">
    <title><%= t :bicimapa %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'adminlte', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="register-page">
    <%= yield %>
  </body>
</html>